---
apiVersion: v1
kind: Service
metadata:
  name: postgrescluster
  labels:
    author: supraja
spec:
  type: ClusterIP
  ports:
    - targetPort: 5432
      port: 80
  selector:
    type: postdb
...
