---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sql-deployment
  labels:
    author: supraja
    app: db
spec:
  replicas: 2
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
        - name: mysql
          image: mysql
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: supraja
...
