---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-nginx
  labels:
    author: supraja
    app: webserver
spec:
  replicas: 2
  selector:
    matchLabels:
      app: proxy
  template:
    metadata:
      labels:
        app: proxy
    spec:
      containers:
        - name: mynginx
          image: nginx
          ports:
            - containerPort: 80
              hostPort: 8080
...
