---
apiVersion: v1
kind: Pod
metadata:
  name: ghost-pod
  namespace: test-ns
  labels:
    author: supraja
    app: cms
spec:
  containers:
    - name: myghost
      image: ghost
      env:
        - name: NODE_ENV
          value: development
...
