---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
  labels:
    type: db
spec:
  replicas: 2  # ✅ Corrected placement
  selector:
    matchLabels:
      type: db
  template:
    metadata:
      labels:
        type: db  # ✅ Ensure this matches the Service selector
    spec:
      containers:
        - name: mydb
          image: postgres
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: secret-value
                  key: password
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: secret-value
                  key: username
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: secret-value
                  key: dbname
...
