---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgressecret
  labels:
    type: db
spec:
  replicas: 2
  selector:
    matchLabels:
      type: db
  template:
    metadata:
      name: postgrespod
      labels:
        type: db
    spec:
      containers:
        - name: mydb
          image: postgres
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: secret2
                  key: password
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: secret2
                  key: username
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: secret2
                  key: dbname
...
