---
apiVersion: v1
kind: Pod
metadata:
  name: mysql-pod
  labels:
    author: supraja
spec:
 containers:
   - name: mysqll
     image: mysql
     env:
       - name: MYSQL_ROOT_PASSWORD
         valueFrom:
           secretKeyRef:
             name: secret1
             key: a
...
